version: 2.1

executors:
  build-agent:
    docker:
      - image: cimg/node:lts
    working_directory: /tmp/diff-tracer
  docker-machine:
    machine: true
    working_directory: /tmp/diff-tracer

jobs:
  test-and-build:
    executor: build-agent
    steps:
      - checkout
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - persist_to_workspace:
          root: /tmp/diff-tracer
          paths:
            - build
            - package.json

  publish-beta:
    executor: docker-machine
    steps:
      - attach_workspace:
          at: /tmp/diff-tracer
      - run: printf "//`node -p \"require('url').parse(process.env.NPM_REGISTRY_URL || 'https://registry.npmjs.org').host\"`/:_authToken=${NPM_TOKEN}\nregistry=${NPM_REGISTRY_URL:-https://registry.npmjs.org}\n" > .npmrc
      - run: npm whoami
      - run: npm publish --access public beta

  publish-latest:
    executor: docker-machine
    steps:
      - attach_workspace:
          at: /tmp/diff-tracer
      - run: printf "//`node -p \"require('url').parse(process.env.NPM_REGISTRY_URL || 'https://registry.npmjs.org').host\"`/:_authToken=${NPM_TOKEN}\nregistry=${NPM_REGISTRY_URL:-https://registry.npmjs.org}\n" > .npmrc
      - run: npm whoami
      - run: npm publish --access public

workflows:
  development:
    jobs:
      - test-and-build:
          filters:
            tags:
              only: /.+/
      - publish-beta:
          requires:
            - test-and-build
          context: npm_publish
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+-.+$/
      - publish-latest:
          requires:
            - test-and-build
          context: npm_publish
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
